stages:
- build
- test
- .post


variables:
  ARTIFACTORY_USERNAME: "admin"
  ARTIFACTORY_PASSWORD: "token"
  GIT_STRATEGY: "empty"

.common-cache: &cache-only-pull
  cache:
    - key: cache-${CI_PROJECT_ID}-${ARCH}
      paths:
        - .cache/
      when: always
      policy: pull
    - key: cache-build-${ARCH}-${CI_PIPELINE_ID}
      unprotect: true
      paths:
        - ${CI_PROJECT_DIR}/build
        - ${CI_PROJECT_DIR}/scripts
        - ${CI_PROJECT_DIR}/Makefile
        - ${CI_PROJECT_DIR}/dist/database
      when: 'always'
      policy: pull
    - key: cache-database-${ARCH}-${CI_PIPELINE_ID}
      unprotect: true
      paths:
        - ${CI_PROJECT_DIR}/database
      when: 'always'
      policy: pull

.common:
  parallel:
    matrix:
      - ARCH:
          - aarch64
          - x86_64
  tags:
    - docker
    - ${ARCH}
    - 8c32g
  variables:
    GIT_SUBMODULE_STRATEGY: "normal"
    GIT_DEPTH: 1
  cache:
    - key: cache-${CI_PROJECT_ID}-${ARCH}
      paths:
        - .cache/
      when: always
    - key: cache-build-${ARCH}-${CI_PIPELINE_ID}
      unprotect: true
      paths:
        - ${CI_PROJECT_DIR}/build
        - ${CI_PROJECT_DIR}/scripts
        - ${CI_PROJECT_DIR}/Makefile
        - ${CI_PROJECT_DIR}/dist/database
      when: 'always'
    - key: cache-database-${ARCH}-${CI_PIPELINE_ID}
      unprotect: true
      paths:
        - ${CI_PROJECT_DIR}/database
      when: 'always'

.artifacts: &artifacts
  name: "hashdata-lightning"
  paths:
    - ${CI_PROJECT_DIR}/dist/packages/manifest*.txt
    - ${CI_PROJECT_DIR}/**/*regression*.out
    - ${CI_PROJECT_DIR}/**/*regression*.diffs
    - ${CI_PROJECT_DIR}/**/results/*
    - ${CI_PROJECT_DIR}/build/test/out/
    - ${CI_PROJECT_DIR}/build/test/failure/
    - ${CI_PROJECT_DIR}/build/test/postgis/*diff
    - ${CI_PROJECT_DIR}/**/gpMgmt/**/*.out
    - ${CI_PROJECT_DIR}/**/gpMgmt/**/*.diff
  when: always
  reports:
    dotenv: ${CI_PROJECT_DIR}/dist/packages/manifest*.txt
  expire_in: 1 week


build_develop:
  stage: build
  extends: .common
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail
    
    git config --global --add safe.directory ${CI_PROJECT_DIR}
    git config --global init.defaultBranch none
    git config --global fetch.recurseSubmodules false
    git config --global credential.interactive never
    git config --global transfer.bundleURI true
    git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@code.hashdata.xyz".insteadOf "https://code.hashdata.xyz"
    
    git init ${CI_PROJECT_DIR}
    cd ${CI_PROJECT_DIR}
    
    # download umbrella repository
    git remote add origin https://code.hashdata.xyz/cloudberry/database/hashdata-lightning-umbrella.git
    git fetch origin --no-recurse-submodules --depth ${GIT_DEPTH}  --prune --quiet
    git checkout -f main
    
    rm -rf ${CI_PROJECT_DIR}/database
    
    # download database repository
    git clone -b ${CI_COMMIT_REF_NAME} --depth ${GIT_DEPTH} ${CI_REPOSITORY_URL} database
    cd ${CI_PROJECT_DIR}/database
    git -c 'submodule.recurse=false' checkout -f -q ${CI_COMMIT_SHA}
    # git lfs pull
    
    # download submodules
    git submodule init
    git submodule sync
    git submodule update --init --depth ${GIT_DEPTH}
    # git submodule foreach 'git lfs pull'
    
    chown -R gpadmin:gpadmin ${CI_PROJECT_DIR}
    cd ${CI_PROJECT_DIR}
    
    export ENV=devel
    
    echo "download dependencies"
    make build-depends
    echo "build database kernel"
    make build-database
    make package-prepare
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual

test_database:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-s -k PGOPTIONS='-c optimizer=off' installcheck" 
    make test-database
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_database-src:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-s -k PGOPTIONS='-c optimizer=off' installcheck" 
    make test-src-test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_pax:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-c default_table_access_method=pax -c optimizer=off -c enable_parallel=off"
    make test-pax
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_vectorization:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-c vector.enable_vectorization=on -c optimizer=off -c enable_parallel=off"
    make test-vectorization
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_database_orca:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-s -k PGOPTIONS='-c optimizer=on' installcheck" 
    make test-database
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_database-src_orca:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-s -k PGOPTIONS='-c optimizer=on' installcheck" 
    make test-src-test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_pax_orca:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-c default_table_access_method=pax -c optimizer=on -c enable_parallel=off"
    make test-pax
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_vectorization_orca:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    export MAKE_TEST_COMMAND="-c vector.enable_vectorization=on -c optimizer=on -c enable_parallel=off"
    make test-vectorization
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

test_parallel:
  stage: test
  extends: .common
  <<: *cache-only-pull
  script: |
    trap 'test -e /tmp/.debugging && tmux new-session -d -s debug && tmux wait-for done' EXIT
    
    env
    set -euxo pipefail

    export ENV=devel
    make test-parallel
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: always
    - if: '$CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME'
      when: always
    - when: manual
  artifacts:
    <<: *artifacts

cleanup-cache:
  stage: .post
  extends: .common
  script: |
    echo "cleanup cache"
    rm -rfv ${CI_PROJECT_DIR}/*
  rules:
    - when: always
