# contrib/cloudberry_fdw/Makefile

MODULE_big = cloudberry_fdw

OBJS = \
	$(WIN32RES) \
	connection.o \
	deparse.o \
	option.o \
	postgres_fdw.o \
	shippable.o

PGFILEDESC = "cloudberry_fdw - foreign data wrapper for Cloudberry"

PG_CPPFLAGS = -I$(libpq_srcdir)
SHLIB_LINK_INTERNAL = $(libpq)

EXTENSION = cloudberry_fdw
DATA = cloudberry_fdw--1.0.sql cloudberry_fdw--1.0--1.1.sql

REGRESS = gp2pg_postgres_fdw gp_postgres_fdw #mpp_postgres_fdw #postgres_fdw
REGRESS += cloudberry_fdw cloudberry_fdw_insert
REGRESS_OPTS += --init-file=$(top_srcdir)/src/test/regress/init_file
REGRESS_OPTS += --ignore-plans

ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
SHLIB_PREREQS = submake-libpq
subdir = contrib/cloudberry_fdw
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif

# compile cbcopy
# all: cbcopy
# cbcopy:
# 	$(MAKE) -f Makefile.cbcopy cbcopy
# .PHONY: cbcopy

# install: install-cbcopy
# install-cbcopy:
# 	$(MAKE) -f Makefile.cbcopy install-cbcopy

export PG_PORT=5432
installcheck: install prep_cloudberry
clean: clean_cloudberry
prep_cloudberry:
	./cloudberry_setup.bash
clean_cloudberry:
	./cloudberry_clean.bash
.PHONY: prep_cloudberry clean_cloudberry
