s3_cluster:
    fs.s3a.endpoint: http://127.0.0.1:8000
    fs.s3a.access.key: admin
    fs.s3a.secret.key: password
    fs.s3a.path.style.access: true
    fs.defaultFS: s3a://
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
