/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

//---------------------------------------------------------------------------
//	@filename:
//		CXformInnerJoin2ParallelHashJoin.cpp
//
//	@doc:
//		Transform inner join to parallel hash join
//---------------------------------------------------------------------------

#include "gpopt/xforms/CXformInnerJoin2ParallelHashJoin.h"

#include "gpos/base.h"

#include "gpopt/operators/CLogicalInnerJoin.h"
#include "gpopt/operators/CPatternLeaf.h"
#include "gpopt/operators/CPhysicalParallelInnerHashJoin.h"
#include "gpopt/operators/CPhysicalParallelTableScan.h"
#include "gpopt/xforms/CXformUtils.h"
#include "gpopt/search/CGroupProxy.h"
#include "gpopt/search/CMemo.h"

// Forward declarations for gpdbwrappers functions
namespace gpdb {
	bool IsParallelModeOK(void);
}

using namespace gpopt;


//---------------------------------------------------------------------------
//	@function:
//		CXformInnerJoin2ParallelHashJoin::FChildrenHaveParallelTableScans
//
//	@doc:
//		Check if child groups contain physical parallel table scans.
//		This ensures parallel hash join is only generated when children
//		are already parallel (coordinated with CXformGet2ParallelTableScan).
//
//		COORDINATION STRATEGY:
//		This xform uses a "wait-for-existing-operators" approach:
//		- CXformGet2ParallelTableScan must run first and generate PhysicalParallelTableScan
//		- Only then will this xform see the parallel operators and generate ParallelHashJoin
//		- This prevents generating parallel joins with non-parallel children
//		- Alternative approaches (xform ordering, group properties) would require
//		  modifying ORCA's core search strategy or property derivation system
//
//---------------------------------------------------------------------------
BOOL
CXformInnerJoin2ParallelHashJoin::FChildrenHaveParallelTableScans(
	CExpressionHandle &exprhdl)
{
	// InnerJoin has 3 children: outer, inner, scalar predicate
	// We check children 0 (outer) and 1 (inner)
	GPOS_ASSERT(exprhdl.Arity() >= 2);

	// Check if handle is attached to a group expression
	// If not, this xform is being evaluated on a standalone expression (not in Memo yet)
	// In that case, we cannot check for existing physical operators
	if (nullptr == exprhdl.Pgexpr())
	{
		return false;
	}

	// Check both outer and inner children for existing parallel table scans
	for (ULONG ulChild = 0; ulChild < 2; ulChild++)
	{
		CGroup *pgroupChild = (*exprhdl.Pgexpr())[ulChild];
		if (nullptr == pgroupChild)
		{
			continue;
		}

		// Scan through all expressions in the child group
		CGroupProxy gpChild(pgroupChild);
		CGroupExpression *pgexprChild = gpChild.PgexprFirst();

		while (nullptr != pgexprChild)
		{
			COperator *popChild = pgexprChild->Pop();

			// Check if this is an existing PhysicalParallelTableScan
			// (already generated by CXformGet2ParallelTableScan)
			if (COperator::EopPhysicalParallelTableScan == popChild->Eopid())
			{
				return true;
			}

			// Also check for parallel hash joins (recursive case)
			// If child is already a parallel join, we can be parallel too
			if (COperator::EopPhysicalParallelInnerHashJoin == popChild->Eopid())
			{
				return true;
			}

			pgexprChild = gpChild.PgexprNext(pgexprChild);
		}
	}

	// No parallel operators found in children
	return false;
}

//---------------------------------------------------------------------------
//	@function:
//		CXformInnerJoin2ParallelHashJoin::CXformInnerJoin2ParallelHashJoin
//
//	@doc:
//		ctor
//
//---------------------------------------------------------------------------
CXformInnerJoin2ParallelHashJoin::CXformInnerJoin2ParallelHashJoin(
	CMemoryPool *mp)
	:  // pattern
	  CXformImplementation(GPOS_NEW(mp) CExpression(
		  mp, GPOS_NEW(mp) CLogicalInnerJoin(mp),
		  GPOS_NEW(mp)
			  CExpression(mp, GPOS_NEW(mp) CPatternLeaf(mp)),  // left child
		  GPOS_NEW(mp)
			  CExpression(mp, GPOS_NEW(mp) CPatternLeaf(mp)),  // right child
		  GPOS_NEW(mp)
			  CExpression(mp, GPOS_NEW(mp) CPatternTree(mp))  // predicate
		  ))
{
}


//---------------------------------------------------------------------------
//	@function:
//		CXformInnerJoin2ParallelHashJoin::Exfp
//
//	@doc:
//		Compute xform promise for a given expression handle;
//
//---------------------------------------------------------------------------
CXform::EXformPromise
CXformInnerJoin2ParallelHashJoin::Exfp(CExpressionHandle &exprhdl) const
{
	// Check if parallel execution is enabled
	// Uses gpdb::IsParallelModeOK() which checks max_parallel_workers_per_gather > 0
	if (!gpdb::IsParallelModeOK())
	{
		return CXform::ExfpNone;
	}

	// Only generate parallel hash join if children already have parallel table scans
	// This ensures coordination with CXformGet2ParallelTableScan
	if (!FChildrenHaveParallelTableScans(exprhdl))
	{
		return CXform::ExfpNone;
	}

	// Use the same logic as regular hash join transformation
	return CXformUtils::ExfpLogicalJoin2PhysicalJoin(exprhdl);
}


//---------------------------------------------------------------------------
//	@function:
//		CXformInnerJoin2ParallelHashJoin::Transform
//
//	@doc:
//		actual transformation
//
//---------------------------------------------------------------------------
void
CXformInnerJoin2ParallelHashJoin::Transform(CXformContext *pxfctxt,
											 CXformResult *pxfres,
											 CExpression *pexpr) const
{
	GPOS_ASSERT(nullptr != pxfctxt);
	GPOS_ASSERT(FPromising(pxfctxt->Pmp(), this, pexpr));
	GPOS_ASSERT(FCheckPattern(pexpr));

	// Only generate parallel hash join if not explicitly disabled
	if (!GPOS_FTRACE(EopttraceDisableInnerHashJoin))
	{
		CXformUtils::ImplementHashJoin<CPhysicalParallelInnerHashJoin>(
			pxfctxt, pxfres, pexpr);
	}
}

// EOF
