ALTER TABLE queries_history
ADD COLUMN mem_peak BIGINT NOT NULL,
ADD COLUMN spill_file_size BIGINT NOT NULL,
ADD COLUMN disk_read BIGINT NOT NULL,
ADD COLUMN disk_write BIGINT NOT NULL;

ALTER FOREIGN TABLE queries_now
ADD COLUMN mem_peak BIGINT NOT NULL,
ADD COLUMN spill_file_size BIGINT NOT NULL,
ADD COLUMN disk_read BIGINT NOT NULL,
ADD COLUMN disk_write BIGINT NOT NULL;

ALTER FOREIGN TABLE queries_tail
ADD COLUMN mem_peak BIGINT NOT NULL,
ADD COLUMN spill_file_size BIGINT NOT NULL,
ADD COLUMN disk_read BIGINT NOT NULL,
ADD COLUMN disk_write BIGINT NOT NULL;

ALTER FOREIGN TABLE _queries_tail
ADD COLUMN mem_peak BIGINT NOT NULL,
ADD COLUMN spill_file_size BIGINT NOT NULL,
ADD COLUMN disk_read BIGINT NOT NULL,
ADD COLUMN disk_write BIGINT NOT NULL;