cluster-1:
    hdfs_namenode_host: mycluster
    hdfs_namenode_port: 9000
    hdfs_auth_method: simple
    is_ha_supported: true
    hadoop_rpc_protection: authentication
    data_transfer_protocol: false
    dfs.nameservices: mycluster
    dfs.ha.namenodes.mycluster: nn1,nn2,nn3
    dfs.namenode.rpc-address.mycluster.nn1: 192.168.176.108:9000
    dfs.namenode.rpc-address.mycluster.nn2: 192.168.178.21:9000
    dfs.namenode.rpc-address.mycluster.nn3: 192.168.178.22:9000
    dfs.client.failover.proxy.provider.mycluster: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailover..

cluster-2:
    hdfs_namenode_host: mycluster
    hdfs_namenode_port: 9000
    hdfs_auth_method: simple
    is_ha_supported: true
    hadoop_rpc_protection: authentication
    data_transfer_protocol: false
    dfs.nameservices: mycluster
    dfs.ha.namenodes.mycluster: nn1,nn2,nn3
    dfs.namenode.rpc-address.mycluster.nn1: 192.168.176.144:9000
    dfs.namenode.rpc-address.mycluster.nn2: 192.168.178.15:9000
    dfs.namenode.rpc-address.mycluster.nn3: 192.168.178.16:9000
    dfs.client.failover.proxy.provider.mycluster: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailover..
