bootstrap.servers:
  - 192.168.176.205:19092
  - 192.168.176.205:19093
  - 192.168.176.205:19094
hdw.catalog.name: hdw_test
hdw.host: localhost
hdw.port: 5432
hdw.user: xxxxx
hdw.password: xxxxxxxxx
hdw.encryptor.password: cn.hashdata.apiary
security.protocol: SASL_PLAINTEXT
sasl.mechanism: SCRAM-SHA-256
sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username = "xxxxx" password = "xxxxx";
prometheus.port: 15888
hive.clusters:
  - hive.gp.name: cluster-1
    hive.cluster.name: cluster-1
    hive.catalog.list:
      - hive.catalog.name: hive
        hdw.database: cluster-1_hive
      - hive.catalog.name: ctg
    hdfs.gp.name: cluster-1
  - hive.gp.name: cluster-2
    hive.cluster.name: cluster-2
    hive.catalog.list:
      - hive.catalog.name: hive
        hdw.database: cluster-2__hive
    hdfs.gp.name: cluster-2